name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CACHE_VERSION: 1  # Increment this to invalidate the cache.
  CI: true
  JAVA_VERSION: 17

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Build Android modules
        run: ./gradlew :pdfium:assembleDebug :pdfpreview:assembleDebug

      - name: Build with Gradle
        run: ./gradlew build
