name: Generate and Publish Dokka

on:
  push:
    tags:
      - '*'  # Run on all tags

env:
  CACHE_VERSION: 1  # Increment this to invalidate the cache.
  CI: true
  JAVA_VERSION: 17

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Generate Dokka documentation
        run: ./gradlew dokkaHtmlMultiModule  # Or your specific Dokka task

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/build/dokka/htmlMultiModule
          publish_branch: main
